### ISSUE TITLE
Problem with charts

### ISSUE THREAD

**Issue by moieric11** [gsoros/GTrader#9]
Hello

I just installed the gtrader on a AMI EC2 Amazon, and the charts are black (not appearing)

Thanks for your help

**Comment by gsoros** [comment]
Hi, have you set up the cron job? It works by periodically fetching the
candlestick data from the exchange and storing it in the local db. You can
do this also by typing "php artisan candles:fetch" in the console.

The software is pre-alpha at the moment so I don't recommend using it as
anything other than a toy.

Good luck!

On 5 Jul 2017 03:13, "moieric11" <notifications@github.com> wrote:

Hello

I just installed the gtrader on a AMI EC2 Amazon, and the charts are black
(not appearing)

Thanks for your help

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gsoros/GTrader/issues/9>, or mute the thread

**Comment by moieric11** [comment]
Hi, thanks for your help

The cronjob work properly, i join you the logs

[laravel.log.txt](https://github.com/gsoros/GTrader/files/1125994/laravel.log.txt)
[schedule.log.txt](https://github.com/gsoros/GTrader/files/1125995/schedule.log.txt)
![gtraderempty](https://user-images.githubusercontent.com/29905535/27884731-97c81a4c-61d5-11e7-91d1-98c1395b6698.jpg)

 i don't see real errors except of  function 'imagecreatetruecolor' not found or invalid function name in /home/ec2-user/GTrader/vendor/davefx/phplot/phplot/phplot.php:690

**Comment by gsoros** [comment]
Hi, looks like GD support is missing from your PHP installation. Try:

sudo yum install php70-gd

**Comment by moieric11** [comment]
Hi,

Yes it's ok right now, needed to install php70-gd

Thanks for help
